stages:
  - test
  - build
  - deploy

teste:
  stage: test
  script: 
    - mvn test -U
  except:
    - tags
    - branches

build:
  stage: build
  script:
    - mvn package -U
  artifacts:
    paths:
      - target/*.war
  only:
    - master

#o deploy vai ser no servidor do integrator via ftp
#build:
 # script: "echo build"
  #environment:
   # name: production
    #url: https://prod.example.com

